### ISSUE TITLE
unable to find module

### ISSUE THREAD

**Issue by tareqdayya** [badcafe/rollup-plugin-inject-process-env#1]
Hi,
Thanks for the package.
Sorry to be your first issue (bound to happen sometime.)
I'm having a problem that i just can't seem to figure out the cause behind it:

`semantic error TS2307 Cannot find module 'rollup-plugin-inject-process-env'.
`

I've looked in the node_modules package, and everything seems fine. That package.json is pointing to the correct main file in dist, same for module and typings. 
PS: The package installs dist but not src.

Here's my rollup.config:

`
import typescript from 'rollup-plugin-typescript2'
import commonjs from 'rollup-plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
// import postcss from 'rollup-plugin-postcss-modules'
import postcss from 'rollup-plugin-postcss'
import resolve from 'rollup-plugin-node-resolve'
import url from 'rollup-plugin-url'
import svgr from '@svgr/rollup'

import pkg from './package.json'
import { terser } from 'rollup-plugin-terser';
import injectProcessEnv from 'rollup-plugin-inject-process-env';

export default {
  input: 'src/index.tsx',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: false
    },
    /* {
       file: pkg.module,
       format: 'es',
       exports: 'named',
       sourcemap: false
     }*/
  ],
  plugins: [
    external(),
    postcss({
      modules: true
    }),
    url(),
    svgr(),
    injectProcessEnv({
      // NODE_ENV: process.env.NODE_ENV,
      // SOME_OBJECT: process.env.REACT_MYKEY,
      // UNUSED: null
      env: {},
    }),
    resolve(),
    typescript({
      rollupCommonJSResolveHack: true,
      clean: true
    }),
    commonjs(),
    (process.env.NODE_ENV === 'production' && terser({
      compress: { drop_console: true }
    })),
  ]
}
`

I've tried messing around with all the (commented) options inside injectProcessEnv, but i guess that's beside the point, the package is not found anyway.

Here's my package.json rollup-related packages:

`
"rollup": "^1.31.0",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-inject-process-env": "^1.1.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-peer-deps-external": "^2.2.2",
    "rollup-plugin-postcss": "^1.6.2",
    "rollup-plugin-terser": "^5.2.0",
    "rollup-plugin-typescript2": "^0.25.3",
    "rollup-plugin-url": "^3.0.1",
    "typescript": "^3.7.5"
`

**Comment by ppoulard** [comment]
Hi,
I really don't understand why it doesn't work so far.
Could you please supply a codesandbox with your configuration ?

**Comment by anicholson** [comment]
@tareqdayya you need to make sure that `typescript()` runs before `injectProcessEnv()` does. Changing the plugin order should solve it. 

I was banging my head against this myself!

**Comment by ppoulard** [comment]
Nice !
I didn't notice that although it is the configuration used by the tests :
https://github.com/badcafe/rollup-plugin-inject-process-env/blob/master/test/myApp/rollup.config.js

Thank you to point it out !
