### ISSUE TITLE
Issues with some other libraries

### ISSUE THREAD

**Issue by lucasmoeskops** [badcafe/rollup-plugin-inject-process-env#2]
When I use this plugin, I get issues with some libraries, like the following:
```

(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/subscriptions-transport-ws/dist/client.js
1: import * as process from 'rollup-plugin-inject-process-env';
2: "use strict";
3: var __assign = (this && this.__assign) || Object.assign || function(t) {
                   ^
4:     for (var s, i = 1, n = arguments.length; i < n; i++) {
5:         s = arguments[i];
...and 5 other occurrences
```

It seems it might be a problem of Rollup itself, but is being triggered by using the module. Do you know a work-around for this?

**Comment by ppoulard** [comment]
2 known workarounds are available :

1. You could use the context option and set it to this: it avoids the rewrite of this to undefined (in fact this is rewritten to... this).
See Rollup documentation:
https://rollupjs.org/guide/en/#error-this-is-undefined
https://rollupjs.org/guide/en/#context

2. You could safely ignore those warnings by adding the onwarn property to your rollup-config.js file:
```
onwarn: function(warning) {
    // Skip certain warnings

    // should intercept ... but doesn't in some rollup versions
    if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }

    // console.warn everything else
    console.warn( warning.message );
}
```
Should work in Angular projects, maybe React too.

**Comment by ppoulard** [comment]
Can you try the last version of rollup-plugin-inject-process-env ?

**Comment by ppoulard** [comment]
v1.3.0 allow to exclude files in node_modules
