### ISSUE TITLE
IE11: 'globalThis' is undefined

### ISSUE THREAD

**Issue by tu4mo** [badcafe/rollup-plugin-inject-process-env#8]
Would it be possible to support IE11?

**Comment by justinformentin** [comment]
Just had this issue. `globalThis` is not available in older browsers. Adding a globalThis polyfill seems to be one way to go about this.

Article with some information: https://mathiasbynens.be/notes/globalthis#alternatives

globalThis shim repo for further ideas on implementation: https://github.com/es-shims/globalThis

**Comment by ppoulard** [comment]
@justinformentin This is a really helpful information that you give us. I've just added a 'Troubleshooting' section in the doc.
